### ISSUE TITLE
LOHAS RGBW

### ISSUE THREAD

**Issue by jbeck22** [digiblur/ESPHome_LOHAS_LED#4]
I used your guide and I have the [LOHAS RGBW](https://www.amazon.com/gp/product/B07T7W7ZMW/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1) bulbs in Home Assistant 0.109.6 without much fuss...so thanks for that!

I was wondering if there is a way to get the "warm white" effect with these same bulbs.  Normally I just want a normal 40 - 60w warm white effect in my bedroom, but sometimes I also want to be able to change the color.  IS that possible?

**Comment by digiblur** [comment]
Do you have the new models or the older with the my9291 drivers?

**Comment by jbeck22** [comment]
They are the older models with the my9291 drivers.

Thank you,

Jeramey Beck
