### ISSUE TITLE
LOHAS RGB+CCT bulb config

### ISSUE THREAD

**Issue by mdeluca1992** [digiblur/ESPHome_LOHAS_LED#5]
I copied the lohas_cct.yaml exactly. I updated the Wifi information and the mqtt information (though I would prefer not to use mqtt with ESPhome). Compiled the yaml and tried to upload to the bulb through the firmware page on Tasmota and keep getting an error saying "Upload Failed Not compatible". 

Any thoughts?

**Comment by digiblur** [comment]
Yep. That's the safety check in Tasmota. Turn it off by going to the console and issuing Setoption78 1

**Comment by mdeluca1992** [comment]
Awesome! Thank you for the quick reply I appreciate it. That did the trick!

**Comment by digiblur** [comment]
No problem...pesky smart people putting in safety measures for us.  HA!  Definitely a good feature though.
