### ISSUE TITLE
Bulb quick flash

### ISSUE THREAD

**Issue by jnpetersen** [digiblur/ESPHome_LOHAS_LED#7]
Using the ESPHome code, I'm just getting the light barely flashing on and then back off regardless of what I do.  Any suggestions on what could be done?

**Comment by digiblur** [comment]
What yaml did you apply and how recent is the bulb?

**Comment by ttcole1254** [comment]
Fwiw, I had to turn off logging on the Lohas CW/WW bulbs I just got. The yaml as it is resulted in a bulb that booted, stayed on the network for a few seconds, dropped off, made the fallback hotspot, and then rebooted. Sometimes it would stay on the network and appear to work fine, but would eventually end up looping again within a day. Only solution was reflashing by soldering dupont wires to the pads. The only change I made was:

```
logger:
  level: NONE
```

With the above change, the bulbs have been rock solid for over 2 weeks now. Not sure if the bulbs have changed or it's possible ESPHome has gotten a little more bloated and logging now doesn't leave enough RAM for the bulbs to be stable, not really sure. The boards in the bulbs look identical.

**Comment by Rami-Pastrami** [comment]
I actually managed to fix the above issue on the most recent version of esphome. it may be that there was a recent revision of bulbs that changed the behind the scenes hardware?


## LOHAS RGBW Smart Bulb with ESPHome

esphome:
  name: namehere
  platform: ESP8266
  board: esp01_1m


wifi:
  ssid: "wifi"
  password: "pass"



logger:
api:


ota:
  password: "4cf43c9442c4087227c786b14c3d820c"



output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO5
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO4
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO13
  - platform: esp8266_pwm
    id: output_warm_white
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_cold_white
    pin: GPIO14


light:
  - platform: rgbww
    name: 'light name'
    red: output_red
    green: output_green
    blue: output_blue
    warm_white: output_warm_white
    cold_white: output_cold_white
    warm_white_color_temperature: 2800 K
    cold_white_color_temperature: 6200 K
    restore_mode: RESTORE_DEFAULT_ON

**Comment by digiblur** [comment]
I would definitely turn this in as bug report to ESPHome so they can get notice of it.

**Comment by Rami-Pastrami** [comment]
not sure if its an esphome issue, since switching out the actual driver in the YAML fixed the issue.

could there have been a hardware change in more recent bulbs causing this problem?

**Comment by digiblur** [comment]
What driver change out? Looks like the same pwm revision bulb?
