### ISSUE TITLE
I think esphome 1.20 kills  lohas_cw_ww.yaml devices

### ISSUE THREAD

**Issue by Styx85** [digiblur/ESPHome_LOHAS_LED#9]
Hi I updated my lohas warmwhite lamps recently after the release of esphome 1.20. Unfortunatly all of them are dead after the update. they give a short flicker, no wifi or even captive portal. so sth seems to go wrong. no issues before that with other esphome versions. 
I use a barebone version of your  lohas_cw_ww.yaml, so nothing special here. so be warned and if anyone has any ideas I would be glad.

**Comment by digiblur** [comment]
I am using the latest on mine and no issues have yet. Luckily you can solder these and see what is crashing them.

**Comment by Styx85** [comment]
That is an interesting information.
Any how, I opened one of the bulbs and soldered it. Flashing works flawlessly, afterwards there is no logger output and no wifi connection. 
I do not know what happened exactly, but it must have killed them. Maybe the short flicker is a hint that sth is still working. also the flashing process is working, so the esp seems to be alive.

**Comment by digiblur** [comment]
You might have to enable the logger if it isn't enabled.  This would help to see why it is crashing.  Hard to kill an ESP chip on the software side without physically damaging it in some way by letting the magic smoke out.
